spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:examen_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true